services:
  - type: web
    name: medical-keyword-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python keyword_app.py
    envVars:
      - key: PORT
        value: 10001
    plan: free
